/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mastermind2;

import java.awt.Color;
import java.awt.event.WindowEvent;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author laurin.agostini
 */
public class CodeChooserWindow extends javax.swing.JFrame {

    MainWindow mainWindow;
    int codeLength;
    String colors;
    /**
     * Creates new form CodeChooserWindow
     */
    public CodeChooserWindow(MainWindow mainWindow, int codeLength, String colors, String code) {
        this.mainWindow = mainWindow;
        this.codeLength = codeLength;
        this.colors = colors;
        initComponents();
        initColorChooser(code);
        this.setSize((codeLength+1) * (colorChooserPrefab.getSize().width + 5), this.getSize().height);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorChooserPanel = new javax.swing.JPanel();
        colorChooserPrefab = new javax.swing.JComboBox<>();
        numbersPanel = new javax.swing.JPanel();
        colorChooserNumberLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose your code");
        setResizable(false);

        colorChooserPrefab.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        colorChooserPrefab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        colorChooserPrefab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        colorChooserPrefab.setMaximumSize(new java.awt.Dimension(35, 25));
        colorChooserPrefab.setMinimumSize(new java.awt.Dimension(35, 25));
        colorChooserPrefab.setPreferredSize(new java.awt.Dimension(35, 25));

        javax.swing.GroupLayout colorChooserPanelLayout = new javax.swing.GroupLayout(colorChooserPanel);
        colorChooserPanel.setLayout(colorChooserPanelLayout);
        colorChooserPanelLayout.setHorizontalGroup(
            colorChooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorChooserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorChooserPrefab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        colorChooserPanelLayout.setVerticalGroup(
            colorChooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorChooserPanelLayout.createSequentialGroup()
                .addComponent(colorChooserPrefab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        colorChooserNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        colorChooserNumberLabel.setText("01");

        javax.swing.GroupLayout numbersPanelLayout = new javax.swing.GroupLayout(numbersPanel);
        numbersPanel.setLayout(numbersPanelLayout);
        numbersPanelLayout.setHorizontalGroup(
            numbersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numbersPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(colorChooserNumberLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        numbersPanelLayout.setVerticalGroup(
            numbersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numbersPanelLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(colorChooserNumberLabel))
        );

        okButton.setText("OK");
        okButton.setToolTipText("");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numbersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorChooserPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(numbersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorChooserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        String code = "";
        for(int i = 0; i < colorChooserPanel.getComponentCount(); ++i){
            code += ((JComboBox)(colorChooserPanel.getComponent(i))).getSelectedItem();
        }
        mainWindow.sendCode(code);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_okButtonMouseClicked


    private void initColorChooser(JComboBox colorChooser, String color){
        colorChooser.setRenderer(new ComboBoxRenderer());
        colorChooser.removeAllItems();
        for(int i = 0; i < colors.length(); ++i){
            colorChooser.addItem("" + colors.charAt(i));
        }
        colorChooser.setSelectedItem(color);
        //colorChooser.setBackground(ComboBoxRenderer.charToColor(color.charAt(0)));
        colorChooser.revalidate();
    }
    
    private String intToString(int i){
        String string = (i < 10? "0" : "");
        string += ((Integer) (i)).toString();
        return string;
    }
    
    private void initColorChooser(String code){
        initColorChooser(colorChooserPrefab, "" + code.charAt(0));
        System.out.println(colorChooserPanel.getComponent(0));
        for(int i = 1; i <  codeLength; ++i){
            JLabel labelClone = new JLabel(intToString(i+1));
            labelClone.setFont(colorChooserNumberLabel.getFont());
            labelClone.setSize(colorChooserNumberLabel.getSize());
            labelClone.setLocation(colorChooserNumberLabel.getLocation().x + i * colorChooserPrefab.getSize().width +(i-1)*5 + 5, colorChooserNumberLabel.getLocation().y);
            
            numbersPanel.add(labelClone);
            
            JComboBox colorChooserClone = new JComboBox();
            initColorChooser(colorChooserClone, "" + code.charAt(i));
            colorChooserClone.setSize(colorChooserPrefab.getSize());
            colorChooserClone.setEditable(colorChooserPrefab.isEditable());
            colorChooserClone.setRenderer(colorChooserPrefab.getRenderer());
            colorChooserClone.setFont(colorChooserPrefab.getFont());
            colorChooserClone.setLocation(colorChooserPrefab.getLocation().x + i * colorChooserPrefab.getSize().width +(i-1)*5 + 5, colorChooserPrefab.getLocation().y);
            
            colorChooserPanel.add(colorChooserClone);
            
        System.out.println(colorChooserPanel.getComponent(i));
        }
        colorChooserPanel.revalidate();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colorChooserNumberLabel;
    private javax.swing.JPanel colorChooserPanel;
    private javax.swing.JComboBox<String> colorChooserPrefab;
    private javax.swing.JPanel numbersPanel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
